# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Goout_IOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
	
# Pods for Goout_IOS
 pod 'Alamofire' 
pod 'SwiftyJSON', '~> 4.0'
pod 'GoogleSignIn'
pod 'AppCenter'
end

