//
//  test_sceneInteractor.swift
//  Goout_IOS
//
//  Created by Salah_4sim2 on 12/11/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol test sceneBusinessLogic
{
  func doSomething(request: test scene.Something.Request)
}

protocol test sceneDataStore
{
  //var name: String { get set }
}

class test sceneInteractor: test sceneBusinessLogic, test sceneDataStore
{
  var presenter: test scenePresentationLogic?
  var worker: test sceneWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: test scene.Something.Request)
  {
    worker = test sceneWorker()
    worker?.doSomeWork()
    
    let response = test scene.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
