//
//  test_sceneWorker.swift
//  Goout_IOS
//
//  Created by Salah_4sim2 on 12/11/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class test sceneWorker
{
  func doSomeWork()
  {
  }
}
