//
//  test_scenePresenter.swift
//  Goout_IOS
//
//  Created by Salah_4sim2 on 12/11/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol test scenePresentationLogic
{
  func presentSomething(response: test scene.Something.Response)
}

class test scenePresenter: test scenePresentationLogic
{
  weak var viewController: test sceneDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: test scene.Something.Response)
  {
    let viewModel = test scene.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
